<a href="https://colab.research.google.com/github/tuta2/api-app/blob/main/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#import Numpy Library
import numpy as np

In [ ]:
#first Numpy array
first_numpy_array = np.array([1,2,3,4])

In [ ]:
print(first_numpy_array)

[1 2 3 4]


In [ ]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
#array with empty numbers
array_with_empty = np.empty((2,3))
array_with_empty

array([[4.81323019e-310, 0.00000000e+000, 2.05833592e-312],
       [6.79038654e-313, 2.14321575e-312, 2.27053550e-312]])

In [30]:
from numpy.core.multiarray import array
#array with arange method
array_arange = np.arange(12)